package org.terash.meeting.entity;

// Generated 2014/02/17 1:32:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Meeting generated by hbm2java
 */
public class Meeting implements java.io.Serializable {

	private BigDecimal rid;
	private String purpose;
	private short period;
	private Date startDate;
	private Date endDate;
	private String place;
	private String topic;
	private String goal;
	private String preparation;
	private Date registerDate;
	private Date modifyDate;
	private Date cancelDate;
	private boolean available;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;
	private String comments;
	private Set minuteses = new HashSet(0);
	private Set meetingMembers = new HashSet(0);
	private Set meetingForms = new HashSet(0);

	public Meeting() {
	}

	public Meeting(BigDecimal rid, String purpose, short period,
			Date startDate, Date endDate, String place, String topic,
			String goal, Date registerDate, boolean available, Date createDate,
			String createUser, Date updateDate, String updateUser) {
		this.rid = rid;
		this.purpose = purpose;
		this.period = period;
		this.startDate = startDate;
		this.endDate = endDate;
		this.place = place;
		this.topic = topic;
		this.goal = goal;
		this.registerDate = registerDate;
		this.available = available;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	public Meeting(BigDecimal rid, String purpose, short period,
			Date startDate, Date endDate, String place, String topic,
			String goal, String preparation, Date registerDate,
			Date modifyDate, Date cancelDate, boolean available,
			Date createDate, String createUser, Date updateDate,
			String updateUser, String comments, Set minuteses,
			Set meetingMembers, Set meetingForms) {
		this.rid = rid;
		this.purpose = purpose;
		this.period = period;
		this.startDate = startDate;
		this.endDate = endDate;
		this.place = place;
		this.topic = topic;
		this.goal = goal;
		this.preparation = preparation;
		this.registerDate = registerDate;
		this.modifyDate = modifyDate;
		this.cancelDate = cancelDate;
		this.available = available;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.comments = comments;
		this.minuteses = minuteses;
		this.meetingMembers = meetingMembers;
		this.meetingForms = meetingForms;
	}

	public BigDecimal getRid() {
		return this.rid;
	}

	public void setRid(BigDecimal rid) {
		this.rid = rid;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public short getPeriod() {
		return this.period;
	}

	public void setPeriod(short period) {
		this.period = period;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getGoal() {
		return this.goal;
	}

	public void setGoal(String goal) {
		this.goal = goal;
	}

	public String getPreparation() {
		return this.preparation;
	}

	public void setPreparation(String preparation) {
		this.preparation = preparation;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set getMinuteses() {
		return this.minuteses;
	}

	public void setMinuteses(Set minuteses) {
		this.minuteses = minuteses;
	}

	public Set getMeetingMembers() {
		return this.meetingMembers;
	}

	public void setMeetingMembers(Set meetingMembers) {
		this.meetingMembers = meetingMembers;
	}

	public Set getMeetingForms() {
		return this.meetingForms;
	}

	public void setMeetingForms(Set meetingForms) {
		this.meetingForms = meetingForms;
	}

}
