package org.terash.meeting.entity;

// Generated 2014/02/17 1:32:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * MeetingGroupMember generated by hbm2java
 */
public class MeetingGroupMember implements java.io.Serializable {

	private BigDecimal rid;
	private Member member;
	private MeetingGroup meetingGroup;
	private boolean available;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;
	private String comments;

	public MeetingGroupMember() {
	}

	public MeetingGroupMember(BigDecimal rid, Member member,
			MeetingGroup meetingGroup, boolean available, Date createDate,
			String createUser, Date updateDate, String updateUser) {
		this.rid = rid;
		this.member = member;
		this.meetingGroup = meetingGroup;
		this.available = available;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	public MeetingGroupMember(BigDecimal rid, Member member,
			MeetingGroup meetingGroup, boolean available, Date createDate,
			String createUser, Date updateDate, String updateUser,
			String comments) {
		this.rid = rid;
		this.member = member;
		this.meetingGroup = meetingGroup;
		this.available = available;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.comments = comments;
	}

	public BigDecimal getRid() {
		return this.rid;
	}

	public void setRid(BigDecimal rid) {
		this.rid = rid;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public MeetingGroup getMeetingGroup() {
		return this.meetingGroup;
	}

	public void setMeetingGroup(MeetingGroup meetingGroup) {
		this.meetingGroup = meetingGroup;
	}

	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
